# ==========================================================
# Server
# ==========================================================
server.port=8080

# ==========================================================
# H2 Database (Development)
# ==========================================================
spring.datasource.url=jdbc:h2:mem:library;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# ==========================================================
# PostgreSQL (Production)
# ==========================================================
# spring.datasource.url=jdbc:postgresql://localhost:5432/library
# spring.datasource.username=postgres
# spring.datasource.password=postgres
# spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================================
# JPA / Hibernate
# ==========================================================
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ==========================================================
# SQL Initialization
# ==========================================================
spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:init.sql
spring.sql.init.data-locations=classpath:inserts.sql

# ==========================================================
# Swagger / OpenAPI
# ==========================================================

# http://localhost:8080/swagger-ui/index.html

# Use the default endpoint:
# http://localhost:8080/v3/api-docs

springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs

# já coloquei fixo no controller
#server.servlet.context-path=/api/v1

# Swagger UI
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/swagger-ui.html

# ==========================================================
# JWT
# ==========================================================
jwt.secret=VerySecretChangeThisKeyForProduction
jwt.expiration-ms=900000
jwt.refresh-expiration-ms=2592000000

# ==========================================================
# Business Rules
# ==========================================================
library.loan.max-books=3
library.loan.min-days=7
library.loan.max-days=14

# ==========================================================
# Error Details (Development Only)
# ==========================================================
server.error.include-message=always
server.error.include-stacktrace=always

# ==========================================================
# Logging (Development Only)
# ==========================================================
logging.level.org.springframework.web=DEBUG
logging.level.org.springdoc=DEBUG