CREATE TABLE role (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(100) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    full_name VARCHAR(150) NOT NULL,
    enabled BOOLEAN NOT NULL DEFAULT TRUE
);

CREATE TABLE user_role (
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (user_id, role_id),
    FOREIGN KEY (user_id) REFERENCES app_user(id),
    FOREIGN KEY (role_id) REFERENCES role(id)
);

CREATE TABLE branch (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    location VARCHAR(255)
);

CREATE TABLE author (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(150) NOT NULL,
    biography VARCHAR(2000)
);

CREATE TABLE book (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    isbn VARCHAR(50) NOT NULL UNIQUE,
    summary VARCHAR(2000),
    price DECIMAL(10,2) DEFAULT 0,
    available BOOLEAN NOT NULL DEFAULT TRUE,
    author_id BIGINT,
    FOREIGN KEY (author_id) REFERENCES author(id)
);

CREATE TABLE inventory_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    book_id BIGINT NOT NULL,
    branch_id BIGINT NOT NULL,
    quantity INT NOT NULL DEFAULT 0,
    unusable_quantity INT NOT NULL DEFAULT 0,
    FOREIGN KEY (book_id) REFERENCES book(id),
    FOREIGN KEY (branch_id) REFERENCES branch(id)
);

CREATE TABLE loan (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    borrower_id BIGINT NOT NULL,
    branch_id BIGINT NOT NULL,
    loan_date TIMESTAMP NOT NULL,
    due_date TIMESTAMP NOT NULL,
    returned_date TIMESTAMP,
    cost DECIMAL(10,2) DEFAULT 0,
    status VARCHAR(30) NOT NULL,
    created_by BIGINT NOT NULL,
    returned_by BIGINT,
    FOREIGN KEY (borrower_id) REFERENCES app_user(id),
    FOREIGN KEY (branch_id) REFERENCES branch(id),
    FOREIGN KEY (created_by) REFERENCES app_user(id),
    FOREIGN KEY (returned_by) REFERENCES app_user(id)
);

CREATE TABLE loan_item (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    loan_id BIGINT NOT NULL,
    book_id BIGINT NOT NULL,
    quantity INT NOT NULL,
    FOREIGN KEY (loan_id) REFERENCES loan(id),
    FOREIGN KEY (book_id) REFERENCES book(id)
);

CREATE TABLE audit_entry (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    action VARCHAR(100) NOT NULL,
    description VARCHAR(2000),
    performed_by BIGINT NOT NULL,
    performed_at TIMESTAMP NOT NULL,
    FOREIGN KEY (performed_by) REFERENCES app_user(id)
);
